"""rack_audit

Revision ID: 4f37d5c552bc
Revises: 
Create Date: 2021-02-12 20:22:06.763267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37d5c552bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=140), nullable=True),
    sa.Column('facillity', sa.String(length=140), nullable=True),
    sa.Column('area', sa.String(length=140), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_area'), 'location', ['area'], unique=False)
    op.create_index(op.f('ix_location_facillity'), 'location', ['facillity'], unique=False)
    op.create_index(op.f('ix_location_place'), 'location', ['place'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_key'), 'user', ['api_key'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=140), nullable=True),
    sa.Column('record_name', sa.String(length=140), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('original_data', sa.Text(), nullable=True),
    sa.Column('updated_data', sa.Text(), nullable=True),
    sa.Column('updated_column', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('audit_status', sa.String(length=20), nullable=True),
    sa.Column('audit_comment', sa.String(length=255), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('safe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=140), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_updated'), 'service', ['updated'], unique=False)
    op.create_table('compartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('safe_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audit_status', sa.String(length=20), nullable=True),
    sa.Column('audit_comment', sa.String(length=255), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['safe_id'], ['safe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('firewall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('alias', sa.String(length=140), nullable=True),
    sa.Column('ipaddress', sa.String(length=140), nullable=True),
    sa.Column('serial', sa.String(length=140), nullable=True),
    sa.Column('manufacturer', sa.String(length=140), nullable=True),
    sa.Column('model', sa.String(length=140), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('rack_position', sa.String(length=10), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('support_start', sa.DateTime(), nullable=True),
    sa.Column('support_end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hsm_domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('network', sa.String(length=140), nullable=True),
    sa.Column('netmask', sa.String(length=140), nullable=True),
    sa.Column('gateway', sa.String(length=140), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.String(length=140), nullable=True),
    sa.Column('environment', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_user',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('alias', sa.String(length=140), nullable=True),
    sa.Column('ipaddress', sa.String(length=140), nullable=True),
    sa.Column('serial', sa.String(length=140), nullable=True),
    sa.Column('manufacturer', sa.String(length=140), nullable=True),
    sa.Column('model', sa.String(length=140), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('rack_position', sa.String(length=10), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('support_start', sa.DateTime(), nullable=True),
    sa.Column('support_end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hsm_backup_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('serial', sa.String(length=140), nullable=True),
    sa.Column('model', sa.String(length=140), nullable=True),
    sa.Column('manufacturedate', sa.String(length=140), nullable=True),
    sa.Column('fbno', sa.String(length=140), nullable=True),
    sa.Column('safe_id', sa.Integer(), nullable=True),
    sa.Column('hsmdomain_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hsmdomain_id'], ['hsm_domain.id'], ),
    sa.ForeignKeyConstraint(['safe_id'], ['safe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hsm_ped',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=140), nullable=True),
    sa.Column('keyno', sa.String(length=140), nullable=True),
    sa.Column('keysn', sa.String(length=140), nullable=True),
    sa.Column('hsmdomain_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('compartment_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['hsm_ped.id'], ),
    sa.ForeignKeyConstraint(['hsmdomain_id'], ['hsm_domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keysn')
    )
    op.create_table('hsm_ped_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=140), nullable=True),
    sa.Column('keyno', sa.String(length=140), nullable=True),
    sa.Column('keysn', sa.String(length=140), nullable=True),
    sa.Column('hsmdomain_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('compartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['hsmdomain_id'], ['hsm_domain.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keysn')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=140), nullable=True),
    sa.Column('role', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('ipaddress', sa.String(length=140), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(length=140), nullable=True),
    sa.Column('cpu', sa.String(length=140), nullable=True),
    sa.Column('psu', sa.String(length=140), nullable=True),
    sa.Column('hd', sa.String(length=140), nullable=True),
    sa.Column('serial', sa.String(length=140), nullable=True),
    sa.Column('model', sa.String(length=140), nullable=True),
    sa.Column('os_name', sa.String(length=140), nullable=True),
    sa.Column('os_version', sa.String(length=140), nullable=True),
    sa.Column('manufacturer', sa.String(length=140), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('support_start', sa.DateTime(), nullable=True),
    sa.Column('support_end', sa.DateTime(), nullable=True),
    sa.Column('rack_position', sa.String(length=10), nullable=True),
    sa.Column('environment', sa.String(length=140), nullable=True),
    sa.Column('virtual_host', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('firewall_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('firewall_id', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('server_if', sa.String(length=140), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['firewall_id'], ['firewall.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hsm_pci_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('serial', sa.String(length=140), nullable=True),
    sa.Column('fbno', sa.String(length=140), nullable=True),
    sa.Column('model', sa.String(length=140), nullable=True),
    sa.Column('manufacturedate', sa.DateTime(), nullable=True),
    sa.Column('safe_id', sa.Integer(), nullable=True),
    sa.Column('hsmdomain_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('support_start', sa.DateTime(), nullable=True),
    sa.Column('support_end', sa.DateTime(), nullable=True),
    sa.Column('contract', sa.String(length=140), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hsmdomain_id'], ['hsm_domain.id'], ),
    sa.ForeignKeyConstraint(['safe_id'], ['safe.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fbno'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('hsm_pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ped_id', sa.Integer(), nullable=True),
    sa.Column('compartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['ped_id'], ['hsm_ped.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('switch_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('server_if', sa.String(length=140), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=140), nullable=True),
    sa.Column('role', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('ipaddress', sa.String(length=140), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(length=140), nullable=True),
    sa.Column('cpu', sa.String(length=140), nullable=True),
    sa.Column('psu', sa.String(length=140), nullable=True),
    sa.Column('hd', sa.String(length=140), nullable=True),
    sa.Column('os_name', sa.String(length=140), nullable=True),
    sa.Column('os_version', sa.String(length=140), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('environment', sa.String(length=140), nullable=True),
    sa.Column('hosting_server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hosting_server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_server')
    op.drop_table('switch_port')
    op.drop_table('hsm_pin')
    op.drop_table('hsm_pci_card')
    op.drop_table('firewall_port')
    op.drop_table('server')
    op.drop_table('hsm_ped_updates')
    op.drop_table('hsm_ped')
    op.drop_table('hsm_backup_unit')
    op.drop_table('switch')
    op.drop_table('service_user')
    op.drop_table('network')
    op.drop_table('hsm_domain')
    op.drop_table('firewall')
    op.drop_table('compartment')
    op.drop_index(op.f('ix_service_updated'), table_name='service')
    op.drop_table('service')
    op.drop_table('safe')
    op.drop_table('rack')
    op.drop_table('audit')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_api_key'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_location_place'), table_name='location')
    op.drop_index(op.f('ix_location_facillity'), table_name='location')
    op.drop_index(op.f('ix_location_area'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
