"""physicalkey

Revision ID: db7c68ad16b1
Revises: 14175e7d08a0
Create Date: 2022-02-14 19:01:39.431288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7c68ad16b1'
down_revision = '14175e7d08a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('compartment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audit_status', sa.String(length=20), nullable=True),
    sa.Column('audit_comment', sa.String(length=255), nullable=True),
    sa.Column('audit_date', sa.DateTime(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['compartment_id'], ['compartment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physical_key')
    # ### end Alembic commands ###
